version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: los
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:80"